### ISSUE TITLE
Support AWS provider v5

### ISSUE THREAD

**Issue by jrsherry** [conda-forge/terraform-provider-aws-feedstock#216]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I require major version 5 of the AWS Terraform provider.  Currently this repo supports v4.63, and PRs are failing CI for subsequent versions in 'azure' tests.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by jrsherry** [comment]
I suspect CI is failing because the golang version needs a bump to v1.20

**Comment by mblum14** [comment]
👍🏽 👍🏽 👍🏽 
This would be huge for my program

**Comment by mblum14** [comment]
@sodre

**Comment by sodre** [comment]
@mblum14, working on it now
